spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:h2:tcp://${DB_HOST}/~/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.orm.jdbc.bind: trace